export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_COMPLETED = 'FETCH_BOOKS_COMPLETED';
export const FETCH_BOOKS_ERRORED = 'FETCH_BOOKS_ERRORED';

export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS';
export const UPDATED_SEARCH_PARAMS_RECEIVED = 'UPDATED_SEARCH_PARAMS_RECEIVED';
