// Book List
export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_COMPLETED = 'FETCH_BOOKS_COMPLETED';

// Search
export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS';
export const UPDATED_SEARCH_PARAMS_RECEIVED = 'UPDATED_SEARCH_PARAMS_RECEIVED';

// Admin
export const ADD_BOOKS = 'ADD_BOOKS';
export const ADD_BOOKS_COMPLETED = 'ADD_BOOKS_COMPLETED';
export const DELETE_ALL_BOOKS = 'DELETE_ALL_BOOKS';
export const DELETE_ALL_BOOKS_COMPLETED = 'DELETE_ALL_BOOKS_COMPLETED';
export const UPDATE_ADMIN_STATE = 'UPDATE_ADMIN_STATE';

// Error
export const ADD_BOOKS_ERRORED = 'ADD_BOOKS_ERRORED';
export const DELETE_ALL_BOOKS_ERRORED = 'DELETE_ALL_BOOKS_ERRORED';
export const FETCH_BOOKS_ERRORED = 'FETCH_BOOKS_ERRORED';
export const DISMISS_ERROR = 'DISMISS_ERROR';
